# Generated by Django 4.2.3 on 2025-12-07 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("persons", "0002_person_artist_name_person_birth_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="user_account",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated user account for login access",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="person",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
